//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comenzales
    {
        public string idcomenzal { get; set; }
        public string nombreComenzal { get; set; }
        public string platosDeGusto { get; set; }
        public string telcomenzal { get; set; }
    }
}
