//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajdores
    {
        public string idtrabajador { get; set; }
        public string tipoDocumento { get; set; }
        public string nomtrabajador { get; set; }
        public string dirTrabajador { get; set; }
        public string telTrabajdor { get; set; }
        public string celTrabajador { get; set; }
    }
}
